
name: Modified CI
jobs:
  Linux:
    strategy:
      fail-fast: false
      matrix:
        include:
        - jdk: 8
        - jdk: 8
          ecj: true
        - jdk: 11
        - jdk: 11
          ecj: true
        - jdk: 17
        - jdk: 17
          ecj: true
        - jdk: 21
        - jdk: 21
          ecj: true
    name: Linux ()
    runs-on: ubuntu-20.04
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-Linux ().csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/jacoco/jacoco', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
    - run: touch optcd-3.txt
    - uses: actions/setup-java@2dfa2011c5b2a0f1489bf9e433881c92c1631f88
      with:
        distribution: zulu
        java-version: |-
          ${{ matrix.jdk }}
          17
    - run: touch optcd-4.txt
    - name: Generate toolchains.xml
      env:
        JDK_VERSION: ${{ matrix.jdk }}
        JDK_HOME_VARIABLE_NAME: JAVA_HOME_${{ matrix.jdk }}_X64
      run: |-
        echo "
        <toolchains>
          <toolchain>
            <type>jdk</type>
            <provides>
              <id>$JDK_VERSION</id>
              <version>$JDK_VERSION</version>
            </provides>
            <configuration>
              <jdkHome>${!JDK_HOME_VARIABLE_NAME}</jdkHome>
            </configuration>
          </toolchain>
        </toolchains>
        " > toolchains.xml
    - run: touch optcd-5.txt
    - name: Build
      run: |-
        ./mvnw -V -B -e --no-transfer-progress \
          verify -Djdk.version=${{ matrix.jdk }} -Dbytecode.version=${{ matrix.jdk }} \
          ${{ matrix.ecj && '-Decj' || ''}} \
          --toolchains=toolchains.xml
    - run: touch optcd-6.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-Linux ()
        path: /home/runner/inotifywait-log-Linux ().csv
  Windows:
    runs-on: windows-2022
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-Windows.csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/jacoco/jacoco', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
    - run: touch optcd-3.txt
    - uses: actions/setup-java@2dfa2011c5b2a0f1489bf9e433881c92c1631f88
      with:
        distribution: zulu
        java-version: |-
          6
          17
    - run: touch optcd-4.txt
    - name: Generate toolchains.xml
      env:
        JDK_VERSION: 6
        JDK_HOME_VARIABLE_NAME: JAVA_HOME_6_X64
      shell: bash
      run: |-
        echo "
        <toolchains>
          <toolchain>
            <type>jdk</type>
            <provides>
              <id>$JDK_VERSION</id>
              <version>$JDK_VERSION</version>
            </provides>
            <configuration>
              <jdkHome>${!JDK_HOME_VARIABLE_NAME}</jdkHome>
            </configuration>
          </toolchain>
        </toolchains>
        " > toolchains.xml
    - run: touch optcd-5.txt
    - name: Build
      shell: bash
      run: |-
        ./mvnw -V -B -e --no-transfer-progress \
          verify -Djdk.version=6 -Dbytecode.version=5 \
          --toolchains=toolchains.xml
    - run: touch optcd-6.txt
    - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874
      id: artifact-upload-step
      with:
        name: jacoco
        path: jacoco/target/*.zip
        if-no-files-found: error
    - run: touch optcd-7.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-Windows
        path: /home/runner/inotifywait-log-Windows.csv
    name: Windows
'on':
- push
- workflow_dispatch
